// SPDX-License-Identifier: MIT
// Code generated by phantom-dns-v2 TDD. DO NOT EDIT.
// Generated file for: internal/transport/known_resolvers.go
package transport

type ResolverSpec struct {
	ID  string
	IP  string
	DoH string
	DoT string
	DoQ string
}

var KnownResolvers = []ResolverSpec{
	{ID: "cloudflare", IP: "1.1.1.1",
		DoH: "https://cloudflare-dns.com/dns-query",
		DoT: "1.1.1.1:853",
		DoQ: "1.1.1.1:853"},
	{ID: "cloudflare-secondary", IP: "1.0.0.1",
		DoH: "https://cloudflare-dns.com/dns-query",
		DoT: "1.0.0.1:853"},
	{ID: "google", IP: "8.8.8.8",
		DoH: "https://dns.google/dns-query",
		DoT: "8.8.8.8:853"},
	{ID: "google-secondary", IP: "8.8.4.4",
		DoH: "https://dns.google/dns-query",
		DoT: "8.8.4.4:853"},
	{ID: "quad9", IP: "9.9.9.9",
		DoH: "https://dns.quad9.net/dns-query",
		DoT: "9.9.9.9:853"},
	{ID: "adguard", IP: "94.140.14.14",
		DoH: "https://dns.adguard-dns.com/dns-query",
		DoT: "94.140.14.14:853",
		DoQ: "94.140.14.14:853"},
	{ID: "mullvad", IP: "194.242.2.2",
		DoH: "https://base.dns.mullvad.net/dns-query",
		DoT: "base.dns.mullvad.net:853"},
	{ID: "nextdns", IP: "45.90.28.0",
		DoH: "https://dns.nextdns.io/",
		DoT: "dns.nextdns.io:853"},
	{ID: "controld", IP: "76.76.2.0",
		DoH: "https://freedns.controld.com/p0",
		DoT: "p0.freedns.controld.com:853"},
}
