// SPDX-License-Identifier: MIT
// Code generated by phantom-dns-v2 TDD. DO NOT EDIT.
// Generated test for: internal/transport/validation_test.go
package transport

import "testing"

func TestValidateNoDirectRoute(t *testing.T) {
	authDomains := []string{"a.example.com", "b.example.net"}
	cases := []struct {
		name    string
		spec    ResolverSpec
		wantErr bool
	}{
		{"clean", ResolverSpec{ID: "x", IP: "1.1.1.1",
			DoH: "https://cloudflare-dns.com/dns-query"}, false},
		{"doh-matches-auth", ResolverSpec{ID: "y", IP: "1.2.3.4",
			DoH: "https://a.example.com/dns-query"}, true},
		{"dot-matches-auth", ResolverSpec{ID: "z", IP: "1.2.3.4",
			DoT: "b.example.net:853"}, true},
		{"doq-matches-auth", ResolverSpec{ID: "w", IP: "1.2.3.4",
			DoQ: "a.example.com:853"}, true},
		{"subdomain-of-auth-matches", ResolverSpec{ID: "s", IP: "1.2.3.4",
			DoH: "https://sub.a.example.com/dns-query"}, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			err := ValidateNoDirectRoute(c.spec, authDomains)
			if (err != nil) != c.wantErr {
				t.Fatalf("err = %v, wantErr = %v", err, c.wantErr)
			}
		})
	}
}

func TestKnownResolvers_AllValidUnderEmptyAuth(t *testing.T) {
	for _, r := range KnownResolvers {
		if err := ValidateNoDirectRoute(r, nil); err != nil {
			t.Errorf("KnownResolver %s rejected by validator: %v", r.ID, err)
		}
	}
}
