// SPDX-License-Identifier: MIT
// Code generated by phantom-dns-v2 TDD. DO NOT EDIT.
// Generated file for: internal/transport/validation.go
package transport

import (
	"errors"
	"fmt"
	"net/url"
	"strings"
)

var ErrAuthDomainAsResolverEndpoint = errors.New(
	"transport: resolver endpoint must not be an auth domain (no-direct-route rule)")

// ValidateNoDirectRoute returns an error if any of spec's DoH/DoT/DoQ
// endpoints resolves to a hostname under one of authDomains. Suffix-based.
func ValidateNoDirectRoute(spec ResolverSpec, authDomains []string) error {
	if len(authDomains) == 0 {
		return nil
	}
	auth := normalizeAuthList(authDomains)
	check := func(label string, raw string) error {
		host := extractHost(raw)
		if host == "" {
			return nil
		}
		h := strings.ToLower(host)
		for _, a := range auth {
			if h == a || strings.HasSuffix(h, "."+a) {
				return fmt.Errorf("%w: %s endpoint %q matches auth domain %q",
					ErrAuthDomainAsResolverEndpoint, label, raw, a)
			}
		}
		return nil
	}
	if err := check("DoH", spec.DoH); err != nil {
		return err
	}
	if err := check("DoT", spec.DoT); err != nil {
		return err
	}
	if err := check("DoQ", spec.DoQ); err != nil {
		return err
	}
	return nil
}

func normalizeAuthList(in []string) []string {
	out := make([]string, 0, len(in))
	for _, a := range in {
		out = append(out, strings.TrimSuffix(strings.ToLower(strings.TrimSpace(a)), "."))
	}
	return out
}

func extractHost(raw string) string {
	if raw == "" {
		return ""
	}
	if strings.HasPrefix(raw, "https://") || strings.HasPrefix(raw, "http://") {
		u, err := url.Parse(raw)
		if err != nil {
			return ""
		}
		return u.Hostname()
	}
	if i := strings.LastIndex(raw, ":"); i >= 0 {
		return raw[:i]
	}
	return raw
}
